spring:
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:postgresql://localhost:5432/delivery
    username: postgres
    password: tkwhckacl
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        highlight_sql: true
  data:
    redis:
      host: localhost
      port: 6379
      username: default
      password: systempass
logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace

jwt:
  secret:
    key: ${JWT_SECRET_KEY}
owner:
  token: ${OWNER_TOKEN}
